api:
  base_url: "https://datosabiertos.bcie.org/api/3/action/datastore_search"
  resource_id: "ce88a753-57f5-4266-a57e-394600c8435d"
  limit: 32000

data:
  raw_path: "data/01-raw/aprobaciones_bcie.csv"
  processed_path: "data/02-preprocessed/aprobaciones_limpias.csv"
  value_col: "Monto_Aprobado"
  group_col: "Pais"

  # Mapeo exacto de las columnas (API actualizada)
  column_renames:
    "ANIO_APROBACION": "Anio_Origen"
    "MONTO_BRUTO_USD": "Monto_Aprobado"
    "PAIS": "Pais"
    "SECTOR_INSTITUCIONAL": "Sector_Economico"

  # Columnas internas
  date_col: "Fecha_Aprobacion"

model:
  monto_bins_usd: [-inf, 100000000.0, 500000000.0, 1000000000.0, inf]
  monto_labels:
    - "Monto < 100M"
    - "Monto 100M–500M"
    - "Monto 500M–1B"
    - "Monto > 1B"
